error[E0502]: cannot borrow `f` as mutable because it is also borrowed as immutable    --> src/day17_elizarov.rs:154:13     | 58  |     let test = |si: usize, i0: usize, j0: usize, len: usize| -> bool {     |                ----------------------------------------------------- immutable borrow occurs here ... 67  |                 if i < len && f[i][j] {     |                               - first borrow occurs due to use of `f` in closure ... 131 |         assert!(test(si, i, j, f.len()));     |                 ---- immutable borrow later used here ... 154 |         put(&mut f, si, i, j);     |             ^^^^^^ mutable borrow occurs here